jobs:
     deploy-netlify:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - run: npm run build
         - uses: netlify/actions/cli@v2
           env:
             NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
             NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

     run-bot:
       needs: deploy-netlify  # Jalankan setelah deploy
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - run: node javascript.js
           env:
             TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
